CREATE DATABASE IF NOT EXIST DBDevMedia;

USE DBDevMedia;

CREATE TABLE Alunos (
    AlunoID INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    Sobrenome VARCHAR(100) NOT NULL,
    Email VARCHAR(150) UNIQUE,
);

